2021-04-08 21:13:28,179 INFO    MainThread:23520 [wandb_setup.py:_flush():69] setting env: {}
2021-04-08 21:13:28,180 INFO    MainThread:23520 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-08 21:13:28,180 INFO    MainThread:23520 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\aleja\Desktop\Tareas\Reconocimiento Visual con Deep Learning\Tarea1\Git\cc7221\tarea1\src\wandb\run-20210408_211328-cqqwrbfd\logs\debug.log
2021-04-08 21:13:28,180 INFO    MainThread:23520 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\aleja\Desktop\Tareas\Reconocimiento Visual con Deep Learning\Tarea1\Git\cc7221\tarea1\src\wandb\run-20210408_211328-cqqwrbfd\logs\debug-internal.log
2021-04-08 21:13:28,180 INFO    MainThread:23520 [wandb_init.py:init():369] calling init triggers
2021-04-08 21:13:28,181 INFO    MainThread:23520 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-08 21:13:28,181 INFO    MainThread:23520 [wandb_init.py:init():418] starting backend
2021-04-08 21:13:28,181 INFO    MainThread:23520 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-04-08 21:13:28,188 INFO    MainThread:23520 [backend.py:ensure_launched():123] starting backend process...
2021-04-08 21:13:28,272 INFO    MainThread:23520 [backend.py:ensure_launched():127] started backend process with pid: 20240
2021-04-08 21:13:28,273 INFO    MainThread:23520 [wandb_init.py:init():423] backend started and connected
2021-04-08 21:13:28,274 INFO    MainThread:23520 [wandb_init.py:init():463] updated telemetry
2021-04-08 21:13:28,275 INFO    MainThread:23520 [wandb_init.py:init():482] communicating current version
2021-04-08 21:13:29,372 INFO    MainThread:23520 [wandb_init.py:init():487] got version response 
2021-04-08 21:13:29,373 INFO    MainThread:23520 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-08 21:13:59,381 INFO    MainThread:23520 [interface.py:_communicate_run():642] couldn't get run from backend
2021-04-08 21:13:59,381 ERROR   MainThread:23520 [wandb_init.py:init():499] backend process timed out
2021-04-08 21:13:59,381 ERROR   MainThread:23520 [wandb_init.py:init():508] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-04-08 21:14:04,687 INFO    MainThread:23520 [wandb_init.py:teardown():187] tearing down wandb.init
